### ISSUE TITLE
Allow Reeborg code editor to zoom

### ISSUE THREAD

**Issue by schellenberg** [sk-opentexts/computerscience20#3]
It would be good to be able to zoom into the text editor, without having all of the UI zoom. This would make any demonstrations being projected on a screen much better!

**Comment by aroberge** [comment]
This is currently possible to do using a clumsy way using the browser's console and enter something like
`editor.getWrapperElement().style["font-size"] = "20px";`

Note that this will only zoom the code in the editor. To increase the code in the library, one needs to replace "editor" by "library". 

I"ve recorded this issue here: https://github.com/aroberge/reeborg/issues/387

Would having some buttons (to increase or decrease the font size) in the "Additional options" menu be an acceptable option?

**Comment by schellenberg** [comment]
Yes, I think having zoom in/out buttons in "Additional options" would work. Perhaps overriding the behaviour of the "cmd+" and "cmd-" keyboards shortcuts would be a good idea as well...

**Comment by schellenberg** [comment]
@aroberge fixed this issue by adding buttons to the editor pane.
